#!/bin/bash
# macos/capture-defaults.sh - Capture current macOS defaults to generate defaults.sh

echo "🔍 Capturing current macOS defaults..."

OUTPUT_FILE="$(dirname "$0")/defaults.sh"
BACKUP_FILE="$(dirname "$0")/defaults.sh.backup.$(date +%Y%m%d_%H%M%S)"

# Backup existing defaults.sh if it exists
if [ -f "$OUTPUT_FILE" ]; then
    echo "📋 Backing up existing defaults.sh to: $BACKUP_FILE"
    cp "$OUTPUT_FILE" "$BACKUP_FILE"
fi

# Start writing the new defaults.sh
cat > "$OUTPUT_FILE" << 'HEADER'
#!/bin/bash
# macos/defaults.sh - macOS system preferences
# Generated by capture-defaults.sh

echo "Setting macOS defaults..."

# Close System Preferences to prevent overriding
osascript -e 'tell application "System Preferences" to quit'

HEADER

echo "# ============================================================================" >> "$OUTPUT_FILE"
echo "# General UI/UX" >> "$OUTPUT_FILE"
echo "# ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Function to safely read and write defaults
capture_default() {
    local domain=$1
    local key=$2
    local description=$3

    # Read current value
    local value=$(defaults read "$domain" "$key" 2>/dev/null)
    local exit_code=$?

    # Skip if the key doesn't exist or value is empty
    if [ $exit_code -ne 0 ] || [ -z "$value" ]; then
        return
    fi

    # Determine the type
    local type="string"

    # Check if it's a boolean (1 or 0)
    if [[ "$value" == "1" ]] || [[ "$value" == "0" ]]; then
        type="bool"
        if [[ "$value" == "1" ]]; then
            value="true"
        else
            value="false"
        fi
    # Check if it's an integer
    elif [[ "$value" =~ ^-?[0-9]+$ ]]; then
        type="int"
    # Check if it's a float
    elif [[ "$value" =~ ^-?[0-9]+\.[0-9]+$ ]]; then
        type="float"
    # Otherwise it's a string - quote it properly
    else
        # Escape quotes in the value
        value="${value//\"/\\\"}"
        value="\"$value\""
    fi

    # Write to output file
    if [ -n "$description" ]; then
        echo "# $description" >> "$OUTPUT_FILE"
    fi

    if [ "$type" == "string" ]; then
        echo "defaults write $domain $key -$type $value" >> "$OUTPUT_FILE"
    else
        echo "defaults write $domain $key -$type $value" >> "$OUTPUT_FILE"
    fi
    echo "" >> "$OUTPUT_FILE"
}

# ============================================================================
# General UI/UX
# ============================================================================

capture_default "com.apple.LaunchServices" "LSQuarantine" "Disable 'Are you sure you want to open' dialog"
capture_default "NSGlobalDomain" "NSNavPanelExpandedStateForSaveMode" "Expand save panel by default"
capture_default "NSGlobalDomain" "NSNavPanelExpandedStateForSaveMode2" "Expand save panel by default"
capture_default "NSGlobalDomain" "PMPrintingExpandedStateForPrint" "Expand print panel by default"
capture_default "NSGlobalDomain" "PMPrintingExpandedStateForPrint2" "Expand print panel by default"
capture_default "NSGlobalDomain" "NSDocumentSaveNewDocumentsToCloud" "Save to disk (not iCloud) by default"
capture_default "com.apple.print.PrintingPrefs" "Quit When Finished" "Auto-quit printer app"
capture_default "com.apple.CrashReporter" "DialogType" "Crash reporter dialog type"
capture_default "NSGlobalDomain" "NSAutomaticQuoteSubstitutionEnabled" "Smart quotes"
capture_default "NSGlobalDomain" "NSAutomaticDashSubstitutionEnabled" "Smart dashes"

echo "# ============================================================================" >> "$OUTPUT_FILE"
echo "# Keyboard & Input" >> "$OUTPUT_FILE"
echo "# ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

capture_default "NSGlobalDomain" "KeyRepeat" "Keyboard repeat rate"
capture_default "NSGlobalDomain" "InitialKeyRepeat" "Initial key repeat delay"
capture_default "NSGlobalDomain" "NSAutomaticSpellingCorrectionEnabled" "Auto-correct"
capture_default "NSGlobalDomain" "AppleKeyboardUIMode" "Full keyboard access"
capture_default "NSGlobalDomain" "ApplePressAndHoldEnabled" "Press-and-hold for keys"

echo "# ============================================================================" >> "$OUTPUT_FILE"
echo "# Trackpad" >> "$OUTPUT_FILE"
echo "# ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

capture_default "com.apple.driver.AppleBluetoothMultitouch.trackpad" "Clicking" "Tap to click"
capture_default "NSGlobalDomain" "com.apple.mouse.tapBehavior" "Tap to click behavior"
capture_default "com.apple.AppleMultitouchTrackpad" "TrackpadThreeFingerDrag" "Three-finger drag"
capture_default "com.apple.driver.AppleBluetoothMultitouch.trackpad" "TrackpadThreeFingerDrag" "Three-finger drag"

echo "# ============================================================================" >> "$OUTPUT_FILE"
echo "# Screen" >> "$OUTPUT_FILE"
echo "# ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

capture_default "com.apple.screensaver" "askForPassword" "Require password after screensaver"
capture_default "com.apple.screensaver" "askForPasswordDelay" "Password delay after screensaver"
capture_default "com.apple.screencapture" "location" "Screenshot location"
capture_default "com.apple.screencapture" "type" "Screenshot format"
capture_default "com.apple.screencapture" "disable-shadow" "Disable screenshot shadow"
capture_default "NSGlobalDomain" "AppleFontSmoothing" "Font smoothing"

echo "# ============================================================================" >> "$OUTPUT_FILE"
echo "# Finder" >> "$OUTPUT_FILE"
echo "# ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

capture_default "com.apple.finder" "AppleShowAllFiles" "Show hidden files"
capture_default "NSGlobalDomain" "AppleShowAllExtensions" "Show all file extensions"
capture_default "com.apple.finder" "ShowStatusBar" "Show status bar"
capture_default "com.apple.finder" "ShowPathbar" "Show path bar"
capture_default "com.apple.finder" "_FXShowPosixPathInTitle" "Show full path in title"
capture_default "com.apple.finder" "_FXSortFoldersFirst" "Sort folders first"
capture_default "com.apple.finder" "FXDefaultSearchScope" "Default search scope"
capture_default "com.apple.finder" "FXEnableExtensionChangeWarning" "File extension change warning"
capture_default "NSGlobalDomain" "com.apple.springing.enabled" "Spring loading for directories"
capture_default "NSGlobalDomain" "com.apple.springing.delay" "Spring loading delay"
capture_default "com.apple.desktopservices" "DSDontWriteNetworkStores" "Avoid .DS_Store on network"
capture_default "com.apple.desktopservices" "DSDontWriteUSBStores" "Avoid .DS_Store on USB"
capture_default "com.apple.finder" "FXPreferredViewStyle" "Preferred view style"
capture_default "com.apple.finder" "WarnOnEmptyTrash" "Warn before emptying trash"
capture_default "com.apple.NetworkBrowser" "BrowseAllInterfaces" "AirDrop over Ethernet"

echo "# ============================================================================" >> "$OUTPUT_FILE"
echo "# Dock" >> "$OUTPUT_FILE"
echo "# ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

capture_default "com.apple.dock" "tilesize" "Dock icon size"
capture_default "com.apple.dock" "mineffect" "Minimize effect"
capture_default "com.apple.dock" "minimize-to-application" "Minimize to application"
capture_default "com.apple.dock" "enable-spring-load-actions-on-all-items" "Spring loading for Dock items"
capture_default "com.apple.dock" "show-process-indicators" "Show indicator lights"
capture_default "com.apple.dock" "launchanim" "Animate opening applications"
capture_default "com.apple.dock" "expose-animation-duration" "Mission Control animation speed"
capture_default "com.apple.dock" "expose-group-by-app" "Group windows by app in Mission Control"
capture_default "com.apple.dock" "autohide-delay" "Auto-hide delay"
capture_default "com.apple.dock" "autohide-time-modifier" "Auto-hide animation time"
capture_default "com.apple.dock" "autohide" "Auto-hide Dock"
capture_default "com.apple.dock" "showhidden" "Translucent hidden apps"
capture_default "com.apple.dock" "show-recents" "Show recent apps"
capture_default "com.apple.dock" "wvous-tl-corner" "Top-left hot corner"
capture_default "com.apple.dock" "wvous-tl-modifier" "Top-left hot corner modifier"

echo "# ============================================================================" >> "$OUTPUT_FILE"
echo "# Safari & WebKit" >> "$OUTPUT_FILE"
echo "# ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

capture_default "com.apple.Safari" "UniversalSearchEnabled" "Universal search"
capture_default "com.apple.Safari" "SuppressSearchSuggestions" "Suppress search suggestions"
capture_default "com.apple.Safari" "ShowFullURLInSmartSearchField" "Show full URL"
capture_default "com.apple.Safari" "IncludeDevelopMenu" "Show Develop menu"
capture_default "com.apple.Safari" "WebKitDeveloperExtrasEnabledPreferenceKey" "Enable Web Inspector"
capture_default "com.apple.Safari" "com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled" "Enable developer extras"
capture_default "com.apple.Safari" "SendDoNotTrackHTTPHeader" "Do Not Track"

echo "# ============================================================================" >> "$OUTPUT_FILE"
echo "# Terminal" >> "$OUTPUT_FILE"
echo "# ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

capture_default "com.apple.terminal" "StringEncodings" "Terminal encodings"
capture_default "com.googlecode.iterm2" "PromptOnQuit" "iTerm2 quit prompt"

echo "# ============================================================================" >> "$OUTPUT_FILE"
echo "# Activity Monitor" >> "$OUTPUT_FILE"
echo "# ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

capture_default "com.apple.ActivityMonitor" "OpenMainWindow" "Open main window on launch"
capture_default "com.apple.ActivityMonitor" "IconType" "Dock icon type"
capture_default "com.apple.ActivityMonitor" "ShowCategory" "Show category"
capture_default "com.apple.ActivityMonitor" "SortColumn" "Sort column"
capture_default "com.apple.ActivityMonitor" "SortDirection" "Sort direction"

echo "# ============================================================================" >> "$OUTPUT_FILE"
echo "# Mac App Store" >> "$OUTPUT_FILE"
echo "# ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

capture_default "com.apple.SoftwareUpdate" "AutomaticCheckEnabled" "Automatic update check"
capture_default "com.apple.SoftwareUpdate" "ScheduleFrequency" "Update check frequency"
capture_default "com.apple.SoftwareUpdate" "AutomaticDownload" "Automatic download"
capture_default "com.apple.SoftwareUpdate" "CriticalUpdateInstall" "Install critical updates"
capture_default "com.apple.commerce" "AutoUpdate" "App auto-update"

echo "# ============================================================================" >> "$OUTPUT_FILE"
echo "# Photos" >> "$OUTPUT_FILE"
echo "# ============================================================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Special handling for currentHost defaults
if defaults -currentHost read com.apple.ImageCapture disableHotPlug &>/dev/null; then
    local value=$(defaults -currentHost read com.apple.ImageCapture disableHotPlug)
    if [[ "$value" == "1" ]]; then
        value="true"
    else
        value="false"
    fi
    echo "# Prevent Photos from opening when devices are plugged in" >> "$OUTPUT_FILE"
    echo "defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool $value" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
fi

# Add special commands that need sudo or other handling
cat >> "$OUTPUT_FILE" << 'FOOTER'
# ============================================================================
# Special Settings (commented out - uncomment if desired)
# ============================================================================

# Restart automatically if the computer freezes
# sudo systemsetup -setrestartfreeze on

# Enable HiDPI display modes (requires restart)
# sudo defaults write /Library/Preferences/com.apple.windowserver DisplayResolutionEnabled -bool true

# Show the ~/Library folder
# chflags nohidden ~/Library

# Show the /Volumes folder
# sudo chflags nohidden /Volumes

# ============================================================================
# Apply changes
# ============================================================================

echo "Killing affected applications..."
for app in "Activity Monitor" \
    "cfprefsd" \
    "Dock" \
    "Finder" \
    "Safari" \
    "SystemUIServer"; do
    killall "${app}" &> /dev/null || true
done

echo "✅ macOS defaults applied! Note that some changes require a logout/restart to take effect."
FOOTER

chmod +x "$OUTPUT_FILE"

echo ""
echo "✅ Captured current macOS defaults to: $OUTPUT_FILE"
echo ""
echo "📋 What was captured:"
echo "  - General UI/UX settings"
echo "  - Keyboard & input preferences"
echo "  - Trackpad settings"
echo "  - Screen & screenshot preferences"
echo "  - Finder preferences"
echo "  - Dock settings"
echo "  - Safari settings"
echo "  - Activity Monitor preferences"
echo "  - Software Update settings"
echo "  - Photos settings"
echo ""
echo "💡 Next steps:"
echo "  1. Review the generated defaults.sh"
echo "  2. Remove any settings you don't want to preserve"
echo "  3. Add any additional settings you care about"
echo "  4. Test by running: source ~/dotfiles/macos/defaults.sh"
echo ""
if [ -f "$BACKUP_FILE" ]; then
    echo "🗂️  Your old defaults.sh was backed up to: $BACKUP_FILE"
fi