#!/bin/bash
# macos/defaults.sh - macOS system preferences
# Generated by capture-defaults.sh

echo "Setting macOS defaults..."

# Close System Preferences to prevent overriding
osascript -e 'tell application "System Preferences" to quit'

# ============================================================================
# General UI/UX
# ============================================================================

# ============================================================================
# Keyboard & Input
# ============================================================================

# Keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 5

# Initial key repeat delay
defaults write NSGlobalDomain InitialKeyRepeat -int 15

# ============================================================================
# Trackpad
# ============================================================================

# Tap to click
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool false

# Three-finger drag
defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerDrag -bool false

# Three-finger drag
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadThreeFingerDrag -bool false

# ============================================================================
# Screen
# ============================================================================

# Screenshot location
defaults write com.apple.screencapture location -string "~/Desktop/screenshots"

# ============================================================================
# Finder
# ============================================================================

# Show path bar
defaults write com.apple.finder ShowPathbar -bool true

# Spring loading for directories
defaults write NSGlobalDomain com.apple.springing.enabled -bool true

# Spring loading delay
defaults write NSGlobalDomain com.apple.springing.delay -float 0.5

# Preferred view style
defaults write com.apple.finder FXPreferredViewStyle -string "clmv"

# ============================================================================
# Dock
# ============================================================================

# Auto-hide Dock
defaults write com.apple.dock autohide -bool true

# ============================================================================
# Safari & WebKit
# ============================================================================

# ============================================================================
# Terminal
# ============================================================================

# ============================================================================
# Activity Monitor
# ============================================================================

# Open main window on launch
defaults write com.apple.ActivityMonitor OpenMainWindow -bool true

# Show category
defaults write com.apple.ActivityMonitor ShowCategory -int 100

# ============================================================================
# Mac App Store
# ============================================================================

# ============================================================================
# Photos
# ============================================================================

# ============================================================================
# Special Settings (commented out - uncomment if desired)
# ============================================================================

# Restart automatically if the computer freezes
# sudo systemsetup -setrestartfreeze on

# Enable HiDPI display modes (requires restart)
# sudo defaults write /Library/Preferences/com.apple.windowserver DisplayResolutionEnabled -bool true

# Show the ~/Library folder
# chflags nohidden ~/Library

# Show the /Volumes folder
# sudo chflags nohidden /Volumes

# ============================================================================
# Apply changes
# ============================================================================

echo "Killing affected applications..."
for app in "Activity Monitor" \
    "cfprefsd" \
    "Dock" \
    "Finder" \
    "Safari" \
    "SystemUIServer"; do
    killall "${app}" &> /dev/null || true
done

echo "✅ macOS defaults applied! Note that some changes require a logout/restart to take effect."
